### ISSUE TITLE
When groups are disabled in Manage groups, Civi sync to mailchimp still overwrites mailchimp.

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#115]
I think the subject is pretty self explanatory, but just in case here is what can be done to reproduce.  We were running a test for a new list we are assembling and it overwrote data in the other MC lists (specifically it removed the interest groupings because our test setup had only the mail lists groups and not interest groups in Civi.)

1.  We disabled all but one of our mailing lists (with its child/interest groups) in Civi by using the disable option on the Civi Manage groups page.  
2. Performed a Civi > Mailchimp sync.

In MC we lost all of our interest grouping data on all groups.  The sync did what it should but ignored the disabled groups.

**Comment by veda-consulting** [comment]
@jason-vivid thanks for reporting, we'll take a look ASAP

**Comment by veda-consulting** [comment]
@jason-vivid we think we've fixed this in the latest version, please confirm.

**Comment by jason-vivid** [comment]
Not working correctly. We disabled the group.  Ran the sync.  Re-enabled the group and ran the sync again, and when we went into Mailchimp after the 2nd sync all of the subscribers had been unsubscribed on our Mailchimp list.

**Comment by shawnholt** [comment]
@jason-vivid I'm trying to follow this scenario.  I see this issue is marked "closed" but you are still having an issue.  In the issue you say "The sync did what it should but ignored the disabled groups." In your comment you say "all of the subscribers had been unsubscribed on our Mailchimp list."

I think it would be helpful to detail the specific issue (perhaps with an example) and if this is not the same issue, then create a new one.  This is collaborative support, so the more effort you put into describing the problem (or better yet the solution!) the better the outcome.

@veda-consulting please correct me if you completely follow the current issue(s).

**Comment by veda-consulting** [comment]
@shawnholt yep, agree.

I think the best bet here is to open a second issue. As @shawnholt has pointed out, we do not get any funding to maintain this extension so if issues are unclear we simply don't have the time to reproduce the issue or understand it. Could I suggest a new issue with the steps. Thanks @jason-vivid, its great that your helping debug.

**Comment by jason-vivid** [comment]
March 16th post by @veda-consulting said to confirm.  I was confirming here that the fix didn't work.

Issue #138 was already started and I listed the same steps as I did above.  I can spell them out a bit more clearly as in what buttons were pushed, etc..  But I think it essentially says that above.  I'll go ahead and script it out in #138 with a lot more detail.  

Thanks for all you guys are doing!
