### ISSUE TITLE
New installation failed

### ISSUE THREAD

**Issue by martin-settle** [veda-consulting/uk.co.vedaconsulting.mailchimp#364]
I just installed the Mailchimp integration extension (CiviCRM 5.77.0 on Wordpress 6.6.2.

Installation seemed to go fine, but when I try to access the Mailchimp settings I get an error message. Thanks in advance for any guidance or help someone could give me. Here is the relevant section from the log file:

2024-09-19 19:05:49+0000  [error] 
$Fatal Error Details = array:3 [
  "message" => "Unable to load template 'file:CRM/Mailchimp/Form/Setting.tpl' in 'file:CRM/Form/default.tpl'"
  "code" => null
  "exception" => SmartyException {#2784
    #message: "Unable to load template 'file:CRM/Mailchimp/Form/Setting.tpl' in 'file:CRM/Form/default.tpl'"
    #code: 0
    #file: "/home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php"
    #line: 196
    trace: {
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:196 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:386 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/uploads/civicrm/templates_c/en_CA/b1/65/e5/b165e53fdf3ac778d487b9b2648fcea2414f29ff_0.file.default.tpl.php:53 {
        content_66ec65ba605871_55084406(Smarty_Internal_Template $_smarty_tpl)
        › 
        ›     <?php $_smarty_tpl->_subTemplateRender($_smarty_tpl->tpl_vars['tplFile']->value, $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0, true);
        › ?>
      }
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:217 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:386 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/uploads/civicrm/templates_c/en_CA/48/19/2f/48192f07a5a9f4a959d20f2d2abd047290bf3f2b_0.file.CMSPrint.tpl.php:100 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:217 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:386 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/uploads/civicrm/templates_c/en_CA/bd/7c/6d/bd7c6db914d120bc436b38708d5301b8ccfe62b9_0.file.wordpress.tpl.php:31 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:123 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:114 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:217 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:238 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:116 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php:117 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php:83 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:355 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php:98 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:299 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:69 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-content/plugins/civicrm/civicrm.php:1231 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-includes/class-wp-hook.php:324 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-includes/class-wp-hook.php:348 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-includes/plugin.php:517 { …}
      /home/MYUSER/public_html/MYDOMAIN/wp-admin/admin.php:259 { …}
    }
  }
]

**Comment by mlutfy** [comment]
PR #365 should fix this.

**Comment by rateditor** [comment]
Hi, this issue remain when try to access mailchimp settings on CiviCRM 6.6.1 & WP 6.8.3.
Is there any update?

**Comment by martin-settle** [comment]
Unfortunately, I abandoned that setup and am now using standalone, and haven't tried linking it back to MailChimp yet.
